name: arc_progress_ring
description: A highly customizable circular progress indicator with milestone markers, glassmorphic effects, and smooth animations for Flutter.
version: 1.0.0
homepage: https://github.com/Sanaullah49/arc_progress_ring
repository: https://github.com/Sanaullah49/arc_progress_ring
issue_tracker: https://github.com/Sanaullah49/arc_progress_ring/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
